# HTTP Server.
server:
  address: ":8000"
  dumpRouterMap: true
  routeOverWrite: true
  accessLogEnabled: true
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# Global logging.
logger:
  level: "all"
  stdout: true

# Database.
database:
  logger:
    level: "all"
    stdout: true

  default:
    link: "mysql:root:123456@tcp(192.168.200.130:3306)/gf_study"
    debug: true

redis:
  default:
    # 以下字段请按需填写你的 Redis 连接信息
    address: "192.168.200.130:6379"     # 例如: "127.0.0.1:6379"
    db: 0              # 例如: 0
    maxIdle: 10
    maxActive: 100
    idleTimeout: 1800            # 单位：秒